### PR TITLE
Give all functions in remotesd_eth.c proper ANSI prototypes

### PR DESCRIPTION
**Pull request by zeldin**
This fixes the build with cc65 V2.17.

### CODE REVIEW

**Comment by lydon42** [comment]
Please use the cc65 commit the submodule is locked to for testing.

**Comment by zeldin** [comment]
Before my change it only worked without `USE_LOCAL_CC65=1` (i.e. when using the submodule).  After my change it works with both `USE_LOCAL_CC65=1` and with the one in the submodule (79018fd424bcf64533f82a19167f25b5fc02d1de).

**Comment by zeldin** [comment]
(I normally use the cc65 in the submodule, but I wanted to check the dependency fix with `USE_LOCAL_CC65=1` as well. :smile:

**Comment by lydon42** [comment]
Our docker build environment (MEGA65/builder-docker) has exactly that cc65 as local installation. Reason is that later commits produce larger code, which makes some of the internal tools to big to be incorporated.
But we will be moving away from cc65 soon, as it as seems to be inferior solution. We will either move to llvm-mos (better code generation) or Calypsi (native 45GS02 code generation).

**Comment by lydon42** [comment]
Btw: drop by on out discord. Or if you already there, give me a ping...

**Comment by zeldin** [comment]
Well, I don't interface all that well with discord...  I don't support you have an IRC channel?

**Comment by zeldin** [comment]
Once there is a discord client for the Mega65 I may reconsider.  :laughing:

**Comment by lydon42** [comment]
Oh, there is a IRC client for the MEGA65? I didn't know that! ;)

**Comment by zeldin** [comment]
If there isn't one already I may make one once I get my Mega65...

**Pull request merged**
