### PR TITLE
#76: MEGA65_FTP: Add 'mount' cmd

### LINKED ISSUE #76: MEGA65_FTP: Add 'mount' command
Provide a 'mount' command to permit the user to mount the .d81 file of their choice.

Simply:

```
mount FILE.D81
```

Could prove handy for people that want immediately follow their recently uploaded .d81 file with a mount too, so they can quickly make use of it.

Thought this could also prove handy for when using xemu with closedrom or openrom, as xemu doesn't presently have the freezer menu functionality.

### PR DESCRIPTION
**Pull request by gurcei**
Resolves #76.

### CODE REVIEW

**Comment by gardners** [comment]
This looks fine, but I am trying to understand what purpose it was created for: It allows mounting a D81 file from the SD card from the mega65_ftp command, but when is that necessary, since freeze menu can be used to mount D81 files.  If it is to make it easier to do from a connected machine, then I would have thought this made more sense to put in m65, rather than in mega65_ftp

**Review by gardners — COMMENTED** [review]
See my previously attached comment.

**Comment by gurcei** [comment]
The initial idea came from Tayger a while back, when he hinted that it might be nice for an end-user that uploaded a .d81 file via m65connect could also mount it without having to visit the freeze-menu as an extra step.

It was an idea I was lukewarm on at that point, but recently, while getting the tcp-comms working between m65/mega65_ftp and xemu, I then found myself in a position where I could upload extra .d81 content into xemu's sd-card image too, but did not have the capability to mount them, as xemu didn't have the freezer mechanism working as yet.

So after experiencing that, my own craving for a 'mount' command grew.

As for whether the home for it should be in mega65_ftp or m65 (or I was even pondering whether it could be a command for m65dbg too), I felt the quickest path to get this working would be via mega65_ftp, as the mounting-logic required a bit of preparation on the m65-side, of setting the dos-filename, triggering the hypervisor trap and such, which felt a little harder to do via m65 (whereas via mega65_ftp, I can easily prepare such steps within the remotesd tool).

**Comment by gardners** [comment]
In that case, I recommend adding it to m65, not mega65_ftp

**Comment by gurcei** [comment]
Just for completeness, we continued the conversation on Discord here:
- https://discord.com/channels/719326990221574164/828380540859449404/854939603814449163

and decided that we'd let this mega65_ftp facility stay as-is for now, but in time, if a common-way could be made for both m65 and mega65_ftp to have a mount command, we can switch over to that method later.

**Pull request merged**
